#!/bin/bash
set -e

# Ensure gh CLI is installed
if ! command -v gh &> /dev/null; then
    echo "Error: GitHub CLI (gh) is not installed."
    echo "Please install it from https://cli.github.com/"
    exit 1
fi

# Get version from new/package.json
VERSION=$(grep -m 1 '"version":' package.json | awk -F '"' '{print $4}')
PRODUCT_NAME="MCP Manager"

echo "Preparing to publish v$VERSION..."

# Build and package using just
just package

echo "Creating GitHub release v$VERSION..."

# The filenames generated by electron-builder for Mac are typically:
# DMG: "${productName}-${version}.dmg"
# Zip: "${productName}-${version}-mac.zip"
# DMG and Zip paths (using wildcards to handle different architectures)
DMG_PATH=$(ls release/${PRODUCT_NAME}-${VERSION}*.dmg | head -n 1)
ZIP_PATH=$(ls release/${PRODUCT_NAME}-${VERSION}*-mac.zip | head -n 1)

# Create the release and upload assets
gh release create "v$VERSION" \
    --title "v$VERSION" \
    --notes "Automated release of ${PRODUCT_NAME} v$VERSION" \
    "$DMG_PATH" \
    "$ZIP_PATH"

echo "Successfully published v$VERSION to GitHub!"
